baseUrl: ""
languageCode: "ja-jp"
title: "小春六花オンリーイベント「小春六花はヨーグルトが食べたい」"
theme: "sakura"
params:
  author: "Nectarition"
  since: 2021
  event:
    logo: "/logotype.png"
    genre: ""
    name: "小春六花はヨーグルトが食べたい"
    subTitle: "小春六花オンリーイベント"
    date: "2021年11月14日(日)"
    place: "サンシャインクリエイション2021 Autumn"
    illustrator: "ジンベイ"
  TwitterScreenName: "nct_kohatabe"
  GoogleAnalyticsMeasuringId: "G-NJN40E6S69"
menu:
  printing:
    - identifier: "eikou"
      name: "栄光"
      url: ""
      isDirect: true
    - identifier: "eikou2"
      name: "栄光２"
      url: ""
      isDirect: true
    - identifier: "eikou3"
      name: "栄光３"
      url: ""
      isDirect: true

markup:
  defaultMarkdownHandler: "goldmark"
  goldmark:
    renderer:
      unsafe: true
